const baseFoods=[
{id:1,name:"Smoky Smash Burger",desc:"Double beef, cheddar, caramelized onion and house sauce.",price:1290,cat:"Burgers",image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85"},
{id:2,name:"Truffle Margherita",desc:"Tomato, mozzarella, basil and a light truffle finish.",price:1650,cat:"Pizza",image:"https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=85"},
{id:3,name:"Crispy Chicken Bowl",desc:"Crispy chicken, seasoned rice, greens and spicy mayo.",price:1190,cat:"Bowls",image:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85"},
{id:4,name:"Creamy Garlic Pasta",desc:"Parmesan, roasted garlic, herbs and silky cream sauce.",price:1390,cat:"Pasta",image:"https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=85"},
{id:5,name:"Fresh Salmon Poke",desc:"Salmon, avocado, sesame, cucumber and rice.",price:1790,cat:"Healthy",image:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85"},
{id:6,name:"Loaded Fries",desc:"Crispy fries topped with cheese, jalapeño and sauce.",price:790,cat:"Sides",image:"https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=85"},
{id:7,name:"Garden Citrus Salad",desc:"Seasonal greens, feta, cucumber and citrus dressing.",price:950,cat:"Healthy",image:"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85"},
{id:8,name:"Berry Pancakes",desc:"Fluffy pancakes, fresh berries, cream and maple syrup.",price:890,cat:"Dessert",image:"https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=900&q=85"},
{id:9,name:"Chicken Tacos",desc:"Grilled chicken, cabbage, salsa and lime crema.",price:990,cat:"Tacos",image:"https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?auto=format&fit=crop&w=900&q=85"},
{id:10,name:"Classic Beef Pizza",desc:"Beef pepperoni, mozzarella, tomato sauce and herbs.",price:1590,cat:"Pizza",image:"https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=900&q=85"},
{id:11,name:"Spiced Chicken Wrap",desc:"Grilled chicken, lettuce, tomato and garlic yogurt.",price:850,cat:"Chicken",image:"https://images.unsplash.com/photo-1521305916504-4a1121188589?auto=format&fit=crop&w=900&q=85"},
{id:12,name:"Mango Lassi",desc:"Creamy yogurt drink blended with ripe mango.",price:490,cat:"Drinks",image:"https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=900&q=85"},
{id:13,name:"Chilli Garlic Noodles",desc:"Wok-tossed noodles, vegetables, sesame and chilli oil.",price:990,cat:"Noodles",image:"https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=900&q=85"},
{id:14,name:"Chocolate Brownie",desc:"Warm chocolate brownie with a soft center.",price:650,cat:"Dessert",image:"https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=85"},
{id:15,name:"Classic Lemonade",desc:"Fresh lemon, chilled water and a light sweetness.",price:390,cat:"Drinks",image:"https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=900&q=85"},
{id:16,name:"Grilled Chicken Plate",desc:"Char-grilled chicken, rice, salad and house dressing.",price:1450,cat:"Chicken",image:"https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=85"}];
const categories=[["🍔","Burgers"],["🍕","Pizza"],["🍜","Noodles"],["🍗","Chicken"],["🥗","Healthy"],["🍰","Dessert"],["🌮","Tacos"],["🥤","Drinks"],["🍝","Pasta"],["🍚","Bowls"],["🍟","Sides"]];
const getFoods=()=>JSON.parse(localStorage.getItem("mzfoods_products")||"null")||baseFoods;
const shipping={standard:{label:"Standard",fee:150},express:{label:"Express",fee:250},"same-day":{label:"Same day",fee:350}};
let cart=JSON.parse(localStorage.getItem("mzfoods_cart")||"[]"), favorites=JSON.parse(localStorage.getItem("mzfoods_favorites")||"[]");
const $=s=>document.querySelector(s), money=n=>"PKR "+Number(n||0).toLocaleString("en-PK");
function save(){localStorage.setItem("mzfoods_cart",JSON.stringify(cart));localStorage.setItem("mzfoods_favorites",JSON.stringify(favorites))}
function toast(t){const el=$("#toast");if(!el)return;el.textContent=t;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),1800)}
function productCard(f){return `<article class="food-card"><div class="food-image"><button class="heart ${favorites.includes(f.id)?"active":""}" data-heart="${f.id}" aria-label="${favorites.includes(f.id)?"Remove":"Add"} ${f.name} ${favorites.includes(f.id)?"from":"to"} favorites"><i class="fa-${favorites.includes(f.id)?"solid":"regular"} fa-heart"></i></button><img src="${f.image}" alt="${f.name}" loading="lazy" width="900" height="650"></div><div class="food-info"><h3>${f.name}</h3><p>${f.desc}</p><div class="food-bottom"><span class="price">${money(f.price)}</span><button class="add-btn" data-add="${f.id}" aria-label="Add ${f.name} to cart">+</button></div><button class="text-link" data-detail="${f.id}">View details</button></div></article>`}
function renderFoods(list=foods,target="#foodGrid"){const el=$(target);if(el)el.innerHTML=list.map(productCard).join("")||`<div class="notice" style="grid-column:1/-1">No food matched your search. Try another name or category.</div>`}
function renderCats(){const el=$("#categoryRow");if(!el)return;el.innerHTML=categories.map((c,i)=>`<button class="category ${i===0?"active":""}" data-cat="${c[1]}" aria-pressed="${i===0}"><div class="category-icon">${c[0]}</div><h3>${c[1]}</h3><small>View menu</small></button>`).join("")}
function renderCart(){const count=cart.reduce((s,x)=>s+x.qty,0);if($("#cartCount"))$("#cartCount").textContent=count;if(!$("#cartItems"))return;const subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0);$("#cartItems").innerHTML=cart.length?cart.map(x=>`<div class="cart-item"><div class="mini"><img src="${x.image}" alt=""></div><div><h4>${x.name}</h4><small>${money(x.price)}</small><div class="qty"><button data-minus="${x.id}" aria-label="Decrease ${x.name} quantity">−</button><span>${x.qty}</span><button data-plus="${x.id}" aria-label="Increase ${x.name} quantity">+</button></div></div><strong>${money(x.price*x.qty)}</strong></div>`).join(""):`<div style="text-align:center;padding:70px 10px;color:#817871;font-size:12px">Your cart is empty.<br>Add something delicious ✨</div>`;if($("#cartTotal"))$("#cartTotal").textContent=money(subtotal)}
function add(id){const f=getFoods().find(x=>x.id===id);if(!f)return;const item=cart.find(x=>x.id===id);item?item.qty++:cart.push({...f,qty:1});save();renderCart();toast(`${f.name} added to cart`);track("add_to_cart",{id:f.id,value:f.price})}
function change(id,d){const i=cart.find(x=>x.id===id);if(!i)return;i.qty+=d;if(i.qty<=0)cart=cart.filter(x=>x.id!==id);save();renderCart()}
function openModal(id){const el=$(id);if(el){el.classList.remove("hidden");document.body.style.overflow="hidden"}}
function closeModal(id){const el=$(id);if(el){el.classList.add("hidden");document.body.style.overflow=""}}
function track(name,params={}){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:name,...params})}
function getUser(){return JSON.parse(localStorage.getItem("mzfoods_user")||"null")||{name:"",email:"",phone:"",image:"",addresses:[]}}
function saveUser(user){localStorage.setItem("mzfoods_user",JSON.stringify(user))}
function addressOptions(){const user=getUser(), list=user.addresses||[], el=$("#checkoutAddress");if(!el)return;el.innerHTML=`<option value="">Select saved address</option>`+list.map(a=>`<option value="${a.id}">${a.label} — ${a.address}${a.default?" (Default)":""}</option>`).join("");const def=list.find(a=>a.default);if(def)el.value=String(def.id)}
function updateCheckoutSummary(){const subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0), method=$("#shippingMethod")?.value||"standard", fee=shipping[method]?.fee||0, total=subtotal+fee;if($("#checkoutSummary"))$("#checkoutSummary").innerHTML=`<div><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div><span>${shipping[method]?.label||"Shipping"}</span><strong>${money(fee)}</strong></div><div class="summary-total"><span>Total</span><strong>${money(total)}</strong></div>`}
function prepareCheckout(){const user=getUser();if(!cart.length)return toast("Your cart is empty");if(!user.addresses?.length){toast("Please add a delivery address in My Profile first");setTimeout(()=>location.href="user-profile.html",600);return}if($("#checkoutForm")){const f=$("#checkoutForm");if(f.name&&user.name)f.name.value=user.name;if(f.phone&&user.phone)f.phone.value=user.phone;addressOptions();updateCheckoutSummary();openModal("#checkoutModal")}}

function isLoggedIn(){const u=JSON.parse(localStorage.getItem("mzfoods_user")||"null");return !!(u&&u.email);}
function initAuthNav(){
  const loggedIn=isLoggedIn();
  document.querySelectorAll("[data-auth-login]").forEach(el=>el.style.display=loggedIn?"none":"");
  document.querySelectorAll("[data-auth-profile]").forEach(el=>el.style.display=loggedIn?"":"none");
  if(location.pathname.endsWith("user-profile.html")&&!loggedIn) location.replace("login.html");
}
function initHeaderSearch(){const box=$("#headerSearchBox"),toggle=$("#headerSearchToggle"),input=$("#headerSearchInput");if(!box||!toggle||!input)return;toggle.addEventListener("click",()=>{const open=box.classList.toggle("open");toggle.setAttribute("aria-expanded",String(open));if(open)setTimeout(()=>input.focus(),30);});document.addEventListener("click",e=>{if(!box.contains(e.target)&&box.classList.contains("open")){box.classList.remove("open");toggle.setAttribute("aria-expanded","false")}});}
async function loadOgImages(){const images=[...document.querySelectorAll("[data-og-url]")];await Promise.all(images.map(async img=>{try{const target=encodeURIComponent(img.dataset.ogUrl);const res=await fetch(`https://api.microlink.io/?url=${target}&meta=true`);if(!res.ok)throw new Error("OG request failed");const data=await res.json();const og=data?.data?.image?.url;if(og){img.src=og;img.classList.remove("is-loading");}}catch(e){img.classList.remove("is-loading");}}));}
function bindGlobal(){renderCart();initAuthNav();initHeaderSearch();loadOgImages();$("#cartBtn")?.addEventListener("click",()=>{openModal("#cartDrawer");openModal("#drawerBackdrop")});$("#closeCart")?.addEventListener("click",()=>{closeModal("#cartDrawer");closeModal("#drawerBackdrop")});$("#drawerBackdrop")?.addEventListener("click",()=>{closeModal("#cartDrawer");closeModal("#drawerBackdrop")});$("#checkoutBtn")?.addEventListener("click",prepareCheckout);$("#menuBtn")?.addEventListener("click",()=>{const b=$("#menuBtn"),n=$("#mobileNav");n.classList.toggle("hidden");b.setAttribute("aria-expanded",String(!n.classList.contains("hidden")))});$("#shippingMethod")?.addEventListener("change",updateCheckoutSummary);$("#contactForm")?.addEventListener("submit",e=>{e.preventDefault();e.target.reset();toast("Message ready — thank you!")});$("#footerSearch")?.addEventListener("submit",e=>e.stopPropagation());document.addEventListener("keydown",e=>{if(e.key==="Escape")["#cartDrawer","#drawerBackdrop","#checkoutModal","#detailModal","#addressModal"].forEach(closeModal)})}
document.addEventListener("click",e=>{const a=e.target.closest("[data-add]");if(a)add(+a.dataset.add);const h=e.target.closest("[data-heart]");if(h){const id=+h.dataset.heart;favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];save();renderFoods(window.currentList||getFoods(),"#foodGrid");renderFoods(window.currentList||getFoods(),"#menuGrid");toast(favorites.includes(id)?"Added to favorites":"Removed from favorites")}const p=e.target.closest("[data-plus]"),m=e.target.closest("[data-minus]");if(p)change(+p.dataset.plus,1);if(m)change(+m.dataset.minus,-1);const d=e.target.closest("[data-detail]");if(d)showDetail(+d.dataset.detail)})
function showDetail(id){const f=getFoods().find(x=>x.id===id),el=$("#detailModal");if(!f||!el)return;$("#detailContent").innerHTML=`<div class="detail-grid"><div class="detail-image"><img src="${f.image}" alt="${f.name}" width="900" height="650"></div><div class="detail-copy"><span class="eyebrow">${f.cat.toUpperCase()}</span><h2>${f.name}</h2><p>${f.desc}</p><div class="detail-meta"><span class="badge">${f.cat}</span><span class="badge">${money(f.price)}</span></div><button class="primary-btn" data-add="${f.id}">Add to cart <span>+</span></button></div></div>`;openModal("#detailModal");track("view_item",{id:f.id,name:f.name})}
function initHome(){renderCats();renderFoods(getFoods().slice(0,8));$("#categoryRow")?.addEventListener("click",e=>{const c=e.target.closest("[data-cat]");if(!c)return;document.querySelectorAll(".category").forEach(x=>{x.classList.remove("active");x.setAttribute("aria-pressed","false")});c.classList.add("active");c.setAttribute("aria-pressed","true");renderFoods(c.dataset.cat==="Burgers"?getFoods().slice(0,8):getFoods().filter(f=>f.cat===c.dataset.cat))});$("#nextCat")?.addEventListener("click",()=>$("#categoryRow").scrollBy({left:250,behavior:"smooth"}));$("#prevCat")?.addEventListener("click",()=>$("#categoryRow").scrollBy({left:-250,behavior:"smooth"}))}
function initMenuPage(){const select=$("#categoryFilter"),search=$("#menuSearch"),sort=$("#sortFilter"),pager=$("#pagination");if(!select||!$("#menuGrid"))return;[...new Set(getFoods().map(f=>f.cat))].sort().forEach(c=>select.insertAdjacentHTML("beforeend",`<option value="${c}">${c}</option>`));const params=new URLSearchParams(location.search);if(params.get("q"))search.value=params.get("q");let pageNo=1,perPage=8;function update(){const q=(search.value||"").toLowerCase().trim(),cat=select.value;let list=getFoods().filter(f=>(f.name+" "+f.desc+" "+f.cat).toLowerCase().includes(q)&&(cat==="all"||f.cat===cat));if(sort.value==="low")list.sort((a,b)=>a.price-b.price);if(sort.value==="high")list.sort((a,b)=>b.price-a.price);if(sort.value==="name")list.sort((a,b)=>a.name.localeCompare(b.name));window.currentList=list;const pages=Math.max(1,Math.ceil(list.length/perPage));pageNo=Math.min(pageNo,pages);renderFoods(list.slice((pageNo-1)*perPage,pageNo*perPage),"#menuGrid");pager.innerHTML=Array.from({length:pages},(_,i)=>`<button class="${i+1===pageNo?"active":""}" aria-label="Page ${i+1}" aria-current="${i+1===pageNo?"page":"false"}">${i+1}</button>`).join("")}[search,select,sort].forEach(x=>x.addEventListener("input",()=>{pageNo=1;update()}));pager.addEventListener("click",e=>{if(e.target.matches("button")){pageNo=+e.target.textContent;update();scrollTo({top:250,behavior:"smooth"})}});update();setTimeout(()=>{if(location.hash==="#menuSearch")search.focus()},80)}
function initPopular(){if($("#menuGrid"))renderFoods(getFoods().filter(f=>[1,2,3,4,6,8].includes(f.id)),"#menuGrid")}
function initAuth(){$("#loginForm")?.addEventListener("submit",e=>{e.preventDefault();const old=getUser();saveUser({...old,email:e.target.email.value,name:old.name||e.target.email.value.split("@")[0],phone:old.phone||"",addresses:old.addresses||[]});toast("Login successful");setTimeout(()=>location.href="user-profile.html",500)});$("#registerForm")?.addEventListener("submit",e=>{e.preventDefault();saveUser({name:e.target.name.value,email:e.target.email.value,phone:e.target.phone?.value||"",image:"",addresses:[]});toast("Account created");setTimeout(()=>location.href="user-profile.html",500)})}
function initProfile(){const form=$("#profileForm");if(!form)return;let user=getUser();form.name.value=user.name||"";form.phone.value=user.phone||"";form.email.value=user.email||"";renderProfileImage(user.image);renderAddresses();$("#profileImage")?.addEventListener("change",e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{user=getUser();user.image=reader.result;saveUser(user);renderProfileImage(reader.result);toast("Profile image updated")};reader.readAsDataURL(file)});form.addEventListener("submit",e=>{e.preventDefault();user=getUser();user.name=form.name.value.trim();user.phone=form.phone.value.trim();user.email=form.email.value.trim();saveUser(user);toast("Profile saved")});$("#newAddressBtn")?.addEventListener("click",()=>{formAddressReset();openModal("#addressModal")});$("#addressForm")?.addEventListener("submit",saveAddress);$("#addressList")?.addEventListener("click",e=>{const edit=e.target.closest("[data-address-edit]"),del=e.target.closest("[data-address-delete]"),def=e.target.closest("[data-address-default]");user=getUser();if(edit){const a=user.addresses.find(x=>x.id===edit.dataset.addressEdit);if(a){const f=$("#addressForm");f.id.value=a.id;f.label.value=a.label;f.address.value=a.address;f.phone.value=a.phone||"";f.default.checked=!!a.default;$("#addressModalTitle").textContent="Edit address";openModal("#addressModal")}}if(del){user.addresses=user.addresses.filter(x=>x.id!==del.dataset.addressDelete);if(user.addresses.length&&!user.addresses.some(x=>x.default))user.addresses[0].default=true;saveUser(user);renderAddresses();toast("Address deleted")}if(def){user.addresses=user.addresses.map(x=>({...x,default:x.id===def.dataset.addressDefault}));saveUser(user);renderAddresses();toast("Default address updated")}})}
function renderProfileImage(src){const el=$("#profilePreview");if(!el)return;el.innerHTML=src?`<img src="${src}" alt="Profile image">`:`<i class="fa-solid fa-user"></i>`}
function renderAddresses(){const el=$("#addressList");if(!el)return;const user=getUser(),list=user.addresses||[];el.innerHTML=list.length?list.map(a=>`<article class="address-card"><div><div class="address-title"><strong>${a.label}</strong>${a.default?'<span class="badge">Default</span>':''}</div><p>${a.address}</p>${a.phone?`<small>${a.phone}</small>`:""}</div><div class="address-actions"><button class="small-btn" data-address-default="${a.id}">Set default</button><button class="small-btn" data-address-edit="${a.id}">Edit</button><button class="small-btn danger" data-address-delete="${a.id}">Delete</button></div></article>`).join(""):`<div class="notice">No saved addresses yet. Add your first delivery address.</div>`}
function formAddressReset(){const f=$("#addressForm");if(!f)return;f.reset();f.id.value="";$("#addressModalTitle").textContent="Add address"}
function saveAddress(e){e.preventDefault();const f=e.target,user=getUser(),id=f.id.value||String(Date.now()),item={id,label:f.label.value.trim(),address:f.address.value.trim(),phone:f.phone.value.trim(),default:f.default.checked};if(!user.addresses)user.addresses=[];if(item.default)user.addresses=user.addresses.map(x=>({...x,default:false}));const i=user.addresses.findIndex(x=>x.id===id);if(i>=0)user.addresses[i]=item;else user.addresses.push(item);if(user.addresses.length===1)user.addresses[0].default=true;if(user.addresses.length&&!user.addresses.some(x=>x.default))user.addresses[0].default=true;saveUser(user);renderAddresses();addressOptions();closeModal("#addressModal");toast("Address saved")}
function initCheckout(){const f=$("#checkoutForm");if(!f)return;$("#shippingMethod")?.addEventListener("change",updateCheckoutSummary);f.addEventListener("submit",e=>{e.preventDefault();const user=getUser(),address=(user.addresses||[]).find(a=>String(a.id)===String(f.address.value)),method=shipping[f.shipping.value]||shipping.standard,subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0),total=subtotal+method.fee;if(!address)return toast("Select a delivery address");cart=[];save();renderCart();closeModal("#checkoutModal");closeModal("#cartDrawer");closeModal("#drawerBackdrop");toast(`Order confirmed — ${method.label} delivery, ${money(total)} total`);track("purchase",{value:total,shipping:method.fee})})}
function initAdmin(){const rows=$("#adminRows"),form=$("#crudForm"),cat=$("#crudCat");if(!rows||!form)return;categories.map(x=>x[1]).forEach(c=>cat.insertAdjacentHTML("beforeend",`<option>${c}</option>`));let data=getFoods().map(x=>({...x}));function draw(){rows.innerHTML=data.map(f=>`<tr><td>${f.name}</td><td>${f.cat}</td><td>${money(f.price)}</td><td><div class="admin-actions"><button class="small-btn" data-edit="${f.id}">Edit</button><button class="small-btn danger" data-delete="${f.id}">Delete</button></div></td></tr>`).join("")}function persist(){localStorage.setItem("mzfoods_products",JSON.stringify(data));draw()}$("#newFoodBtn")?.addEventListener("click",()=>{form.reset();form.elements.id.value="";$("#crudTitle").textContent="Add food";openModal("#crudModal")});rows.addEventListener("click",e=>{const del=e.target.closest("[data-delete]"),edit=e.target.closest("[data-edit]");if(del){const id=+del.dataset.delete;if(confirm("Delete this menu item?")){data=data.filter(f=>f.id!==id);persist();toast("Food deleted")}}if(edit){const f=data.find(x=>x.id==edit.dataset.edit);if(!f)return;Object.keys(f).forEach(k=>{if(form[k])form[k].value=f[k]});$("#crudTitle").textContent="Edit food";openModal("#crudModal")}});form.addEventListener("submit",e=>{e.preventDefault();const v=Object.fromEntries(new FormData(form));const item={id:v.id?+v.id:Date.now(),name:v.name,desc:v.desc,price:+v.price,cat:v.cat,image:v.image};if(v.id)data=data.map(f=>f.id===+v.id?item:f);else data.push(item);persist();closeModal("#crudModal");toast(v.id?"Food updated":"Food created")});draw()}
function init(){bindGlobal();initMenuPage();initHome();if(location.pathname.endsWith("popular.html"))initPopular();initAuth();initProfile();initCheckout();initAdmin();document.querySelectorAll("[data-close]").forEach(b=>b.addEventListener("click",()=>closeModal(b.dataset.close)));}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
